services:
  backend-nest-development:
    build:
      context: ./app
      dockerfile: ./docker/development/Dockerfile
    tty: true
    hostname: backend
    container_name: backend-nest-development
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ./app
        target: /app
    ports:
      - "0.0.0.0:3000:3000/tcp"
    networks:
      - backend
    env_file:
      - app/.env

networks:
  backend: