export const INVALID_PARAMETERS = 'COMMON.INVALID_PARAMETERS' as const;

export const ACCOUNT_ALREADY_EXISTS = 'ACCOUNT.ALREADY_EXISTS' as const;
export const ACCOUNT_DOES_NOT_EXIST = 'ACCOUNT.DOES_NOT_EXIST' as const;
