export const INVALID_PARAMETERS = 'COMMON.INVALID_PARAMETERS' as const;

export const UNAUTHENTICATED = 'AUTH.UNAUTHENTICATED' as const;

export const PROJECT_ALREADY_EXISTS = 'PROJECT.ALREADY_EXISTS' as const;
export const PROJECT_DOES_NOT_EXIST = 'PROJECT.DOES_NOT_EXIST' as const;
